version: '3'

volumes:
  service_db:
    driver: local
  pgadmin:
    driver: local

services:
  app:
    image: webdevops/php-nginx:8.2-alpine
    hostname: service
    working_dir: /app
    volumes:
      - .:/app
      - .deploy/nginx/conf.d/nginx.conf:/opt/docker/etc/nginx/vhost.conf
      - .deploy/nginx/conf.d/nginx.conf:/nginx/conf.d/
    ports:
      - "8080:80"

  pg:
    image: postgres:13-alpine
    hostname: service_db
    ports:
      - "5432:5432"
    volumes:
      - service_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@cic.kz
      PGADMIN_DEFAULT_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "7313:80"
    stdin_open: true
    depends_on:
      - pg
    volumes:
      - pgadmin:/var/lib/pgadmin
      - .dev/pgadmin4/servers.json:/pgadmin4/servers.json
